### ISSUE TITLE
Cant install via pip

### ISSUE THREAD

**Issue by OGKevin** [prexview/prexview-python#2]
I want to try this out but unfortunately i cant install the python library via pip ill get this error msg

` Could not find a version that satisfies the requirement prexview (from versions: )
No matching distribution found for prexview` 

Did you guys set it up correctly with PyPi ?

**Comment by danioso** [comment]
@OGKevin I'm going to check the setup because I'm getting the same error msg

**Comment by sanosom** [comment]
Thank you @OGKevin!

This is our first python module, and we didn't know well how to publish correctly the module on PyPI.

I fixed it, now you will be able to use it without any problem.

**Comment by OGKevin** [comment]
No problem happy to help 😊
