### ISSUE TITLE
python 3.8

### ISSUE THREAD

**Issue by empereira** [prexview/prexview-python#3]
Hello,

It's compatible with python 3.8?

I tried, but the error occurs:

`400 Client Error: Bad Request for url: https://api.prexview.com/v1/transform
`

**Comment by sanosom** [comment]
Hi @empereira,

I've tried this on python 3.8.5 and I could generate the PDF file successfully.

```
santi@DESKTOP:/mnt/c/Users/Santi/Workspace/prexview/prexview-python$ python --version
Python 3.8.5
santi@DESKTOP:/mnt/c/Users/Santi/Workspace/prexview/prexview-python$ python generate_pdf.py
File created: my_pdf.pdf
```

Can you please check if you put your API_KEY correctly or if the template/design used is already created in prexview service?

**Comment by ayushsingh1601** [comment]
Hi, 
I am getting the same error as @empereira on python 3.8.0 on the sample code itself.

`from prexview import PrexView

pxv = PrexView('.....mykey...')

options = {'template': 'custom_invoice', 'output': 'pdf','templateBackup': 'supported_languages'}

json = {
  'languages': [
    {'code': 'en', 'name': 'English'},
    {'code': 'es', 'name': 'Spanish'},
    {'code': 'fr', 'name': 'French'}
  ]
}

file = 'test1.pdf'

try:
  res = pxv.sendJSON(json, options)

  with open(file, 'wb') as f:
    f.write(res['file'])
    f.close()

  print ('File created:', file)
except Exception as e:    
    print("FILE CREATION FAILED: %s "%(e))
`
What could be going wrong?

**Comment by sanosom** [comment]
So, I've just found that we are not parsing the API returned error, so you just see a simple HTTPError with a 400 status, I've created a PR in order to improve it.

**Comment by sanosom** [comment]
> Hi,
> I am getting the same error as @empereira on python 3.8.0 on the sample code itself.
> 
> `from prexview import PrexView
> 
> pxv = PrexView('.....mykey...')
> 
> options = {'template': 'custom_invoice', 'output': 'pdf','templateBackup': 'supported_languages'}
> 
> json = {
> 'languages': [
> {'code': 'en', 'name': 'English'},
> {'code': 'es', 'name': 'Spanish'},
> {'code': 'fr', 'name': 'French'}
> ]
> }
> 
> file = 'test1.pdf'
> 
> try:
> res = pxv.sendJSON(json, options)
> 
> with open(file, 'wb') as f:
> f.write(res['file'])
> f.close()
> 
> print ('File created:', file)
> except Exception as e:
> print("FILE CREATION FAILED: %s "%(e))
> `
> What could be going wrong?

After running the code you put here, I've found that I didn't have a template called `custom_invoice`, I have to create it in PrexView in order to use it, can you take a look and see if you already have it created?
